version: '3.8'
services:
 postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345rdx
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

 airflow:
    image: apache/airflow:2.2.3
    command: webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:12345rdx@postgres/postgres
      - AIRFLOW__WEBSERVER__SECRET_KEY=88ec3975c0e4ee49cc3108c7bdd8cae5760b412c89b743dcda40d77b5bf9
      
    ports:
      - "8082:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow.cfg:/usr/local/airflow/airflow.cfg
    depends_on:
      - postgres

 dbt:
    image: fishtownanalytics/dbt:0.21.0
    command: dbt run
    volumes:
      - ./dbt:/usr/app/dbt
    depends_on:
      - postgres

 redash:
    image: redash/redash:latest
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
 postgres_data: